app/urls.py
from django.urls import path
from . import views
app_name = 'app'
urlpatterns = [
    path('', views.index, name = 'index'),
    path('projekt1/', views.projekt1, name='projekt1'),
    path('projekt2/', views.projekt2, name='projekt2'),
]

pwi/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
]

app/models.py
from django.db import models

# Create your models here.

app/views.py
from django.shortcuts import render, HttpResponse
from django.utils.encoding import smart_str
from django.core.files import File
def index(request):
    #Home page of Learning Log
    return render(request, 'app/index.html')

def projekt1(request):
    #Home page of Learning Log
    return render(request, 'app/projekt1.html')

def projekt2(request):
    #Home page of Learning Log
    return render(request, 'app/projekt2.html')
def download_file(request):
    file_name = 'kod.zip'
    #path_to_file = static('app/images/tronn.png')
    response = HttpResponse(content_type='application/force-download')
    response['Content-Disposition'] = 'attachment; filename=%s' % smart_str(file_name)
    return response

app/templates/app/base.html
<!doctype html>
{% load static %}
<html lang="pl">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Informatyka</title>
    {% load bootstrap4 %}
    {% bootstrap_css%}
	{% load i18n %}
    {% bootstrap_javascript jquery="full"%}
	<script src="http://code.jquery.com/jquery-1.9.1.min.js"></script>
  </head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <a class="navbar-brand" href="#">{% trans "Informatics SGGW" %}</a>
	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarColor01">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <button type="button" class="btn btn-primary">{% trans "About the faculty" %}</button> <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a href="#o_kierunku" onclick="show_about_me()"><button type="button" class="btn btn-primary">{% trans "About direction" %}</button></a>
      </li>
      <li class="nav-item">
        <a href="#program" onclick="show_projects()"><button type="button" class="btn btn-primary">{% trans "Program" %}</button></a>
      </li>
      <li class="nav-item">
        <a href="#kontakt" onclick="show_contact()"><button type="button" class="btn btn-primary">{% trans "Contact" %}</button></a>
      </li>
    </ul>
  </div>
</nav>
	<link rel="stylesheet" href = "{% static 'css/projekt1style.css' %}" type = "text/css"/>
{% block content %}

{% endblock %}
	<table class="table table-hover">
                <thead>
                    <tr class="default">
                        <td>Copyright©cinek21954s.pythonanywhere.com</td>
                    </tr>
                </thead>
	</table> 
</body>
</html>

app/templates/app/index.html
{% extends "app/base.html" %}
{% load static %}
{% block content %}
{% load i18n %}
	<div class="jumbotron">
		<section id="first" class="page">
		  <h1 class="display-3">WZIM</h1>
		  <hr class="my-4">
		  <p>{% trans "The Faculty of Applied Informatics and Mathematics was established on January 1, 2008 on the basis of the Interfaculty Study of Computer Science and Econometrics (later called: Interfaculty Study of Computer Science Applications). The study was established by the Senate of the Warsaw University of Life Sciences (SGGW) on 24 January 2001. The aim of the study was to educate students in computer science and econometrics using the SGGW didactic base. The classes were conducted mainly by SGGW scientific staff dealing with mathematics and IT, employed in various University organizational units." %}</p>
		  <p class="lead">
			<a class="btn btn-primary btn-lg" href="http://www.wzim.sggw.pl/wydzial/prezentacja-wydzialu/" role="button">{% trans "Read more." %}</a>
		  </p>
		</section>
		<section id="second" class="page">
		  <h1 class="display-3">{% trans "Informatics" %}</h1>
		  <p class="lead">{% trans "Studying computer science at SGGW, you will learn, among others, about:" %}</p>
		  <hr class="my-4">
			<table class="table table-hover">
					<tr class="table-secondary">
						<td>{% trans "Physical foundations of information theory" %}</td>
						<td></td>
					</tr>
					<tr class="table-secondary">
						<td>{% trans "Information protection and cryptology" %}</td>
						<td></td>
					</tr>
					<tr class="table-secondary">
						<td>{% trans "Computer networks (CISCO technologies)" %}</td>
						<td></td>
					</tr>
					<tr class="table-secondary">
						<td>{% trans "Security of computer networks and systems" %}</td>
						<td></td>
					</tr>
					<tr class="table-secondary">
						<td>{% trans "Wireless communications and mobile systems" %}</td>
						<td></td>
					</tr>
					<tr class="table-secondary">
						<td>{% trans "Diagnostics of analog systems" %}</td>
						<td></td>
					</tr>
					<tr class="table-secondary">
						<td>{% trans "Computer vision" %}</td>
						<td></td>
					</tr>
			</table>
		</section>
		<section id="third" class="page">
		  <h1 class="display-3">{% trans "Program" %}</h1>
		  <p class="lead">{% trans "The program for the first semester is presented below." %}</p>
		  <hr class="my-4">
		  <blockquote class="blockquote">
				<p class="mb-0"><h4>{% trans "General description of the abbreviations:" %}</h4></p>
				<p>
					<h6>{% trans "N - number" %} </h6>
					<h6>{% trans "h - hours" %}</h6>
					<h6>{% trans "lec - lecture" %} </h6>
					<h6>{% trans "exe - exercises" %}</h6>
					<h6>{% trans "lab - laboratory" %}</h6>
				</p>
				<p class="mb-0"><h4>{% trans "Description of class status symbols:" %}</h4></p>
				<p>
					<h6>{% trans "P - basic classes" %} </h6>
					<h6>{% trans "O - obligatory classes" %} </h6>
					<h6>{% trans "N - general academic profile " %}</h6>
				</p>
				<hr class="my-4"></hr>
		   </blockquote>
			<table class="table table-hover">
					<thead>
					<tr class="table-active">
						<th scope="col">{% trans "The name of an object" %}</th>
						<th scope="col">{% trans "N.h. lec." %}</th>
						<th scope="col">{% trans "N.h. exe." %}</th>
						<th scope="col">{% trans "N.h. exe. lab." %}</th>=
						<th scope="col">{% trans "Credit type" %}</th>
						<th scope="col">{% trans "ECTS" %}</th>
						<th scope="col">{% trans "Statuses" %}</th>
					</tr>
					</thead>
					<tbody>
					<tr class="table-light">
						<td>{% trans "Introduction to programming" %}</td>
						<td>30</td>
						<td>0</td>
						<td>30</td>=
						<td>{% trans "Exam" %}</td>
						<td>6</td>
						<td>P,O,N</td>
					</tr>
					<tr class="table-light">
						<td>{% trans "Basics of mathematical analysis" %}</td>
						<td>30</td>
						<td>30</td>
						<td>0</td>=
						<td>{% trans "Exam" %}</td>
						<td>6</td>
						<td>P,O,N</td>
					</tr>
					<tr class="table-light">
						<td>{% trans "Fundamentals of higher mathematics" %}</td>
						<td>30</td>
						<td>30</td>
						<td>0</td>=
						<td>{% trans "Exam" %}</td>
						<td>5</td>
						<td>P,O,N</td>
					</tr>
					<tr class="table-light">
						<td>{% trans "Discrete mathematics 1" %}</td>
						<td>30</td>
						<td>30</td>
						<td>0</td>=
						<td>{% trans "Exam" %}</td>
						<td>5</td>
						<td>P,O,N</td>
					</tr>
					<tr class="table-light">
						<td>{% trans "Fundamentals of Physics" %}</td>
						<td>30</td>
						<td>30</td>
						<td>0</td>=
						<td>{% trans "Exam" %}</td>
						<td>5</td>
						<td>P,O,N</td>
					</tr>
					<tr class="table-light">
						<td>{% trans "Algorithmic reasoning" %}</td>
						<td>30</td>
						<td>0</td>
						<td>0</td>=
						<td>{% trans "Rating" %}</td>
						<td>2</td>
						<td>P,O</td>
					</tr>
					<tr class="table-light">
						<td>{% trans "Ergonomics and OHS" %}</td>
						<td>15</td>
						<td>0</td>
						<td>0</td>
						<td>{% trans "Rating" %}</td>
						<td>1</td>
						<td>P,O</td>
					</tr>
					</tbody>
			</table>
		</section>
		<section id="fourth" class="page">
		  <h1 class="display-3">{% trans "Contact" %}</h1>
		  <hr class="my-4">
		  <div class="card bg-light mb-3" style="max-width: 20rem;">
		  <div class="card-header">{% trans "Forms of contact" %}</div>
			  <div class="card-body">
				<h4 class="card-title">Mail</h4>
				<p class="card-text">wzim@sggw.pl</p>
				<h4 class="card-title">{% trans "Telephone" %}</h4>
				<p class="card-text">(22) 59 372 12</p>
				<p class="card-text">(22) 59 372 13</p>
				<p class="card-text">(22) 59 372 15</p>
			  </div>
		  </div>
		</section>
		<section id="cookie-warn">
			<p><strong>{% trans "ATTENTION!" %}</strong> {% trans "This website uses cookies. Information obtained through cookies are mainly used for statistical purposes. Staying on you agree to save them in your browser." %} 
			<a href="javascript:void(0);" id="close-cookie-warn"
			>{% trans "Close the warning" %}</a></p>
</section>
	</div>
<script src="{% static 'js/spa.js' %}"></script>
<script src="{% static 'js/projekt1js.js' %}"></script>
{% endblock%}

app/templates/app/projekt1.html
{% extends "app/base.html" %}
{% load static %}
{% block content %}
<link rel="stylesheet" href = "{% static 'css/projekt1style.css' %}" type = "text/css"/>
<div class="main">
	<div class="top">
		<div class="topb">
			<div class="topblf"><a href="{% url 'app:index'%}">Home</a></div>
			<div class="topbl1"><a href="">About me</a></div>
			<div class="topbl2"><a href="">Projects</a></div>
			<div class="topbl2"><a href="">Contact</a></div>
			<div class="clear"></div>
		</div>
		<div class="topa">Tic Tac Toe</div>
	</div>
	<div class="center">
		<div class="centerc">
			<span id="0" class="firstlefttop"> - </span><span id="1" class="pointertop"> - </span><span id="2" class="pointertop"> - </span> <br />
			<span id="3" class="firstleft"> - </span><span id="4" class="pointer"> - </span><span id="5" class="pointer"> - </span> <br />
			<span id="6" class="firstleft"> - </span><span id="7" class="pointer"> - </span><span id="8" class="pointer"> - </span> <br />
			<p id="status" class="marginl">Zaczyna gracz X</p>
			<div class="marginl">
				<button id="reset">Reset</button>
			</div>
		</div>	
	</div>
</div>
<script src="{% static 'js/projekt1js.js' %}"></script>
{%endblock content%}

app/templates/app/projekt2.html
{% extends "app/base.html" %}
{% load static %}
{% block content %}
<link rel="stylesheet" href = "{% static 'css/projekt2style.css' %}" type = "text/css"/>
<div class="main">
	<div class="top">
		<div class="topb">
			<div class="topblf"><a href="{%url 'app:index'%}">Home</a></div>
			<div class="topbl1"><a href="">About me</a></div>
			<div class="topbl2"><a href="">Others</a></div>
			<div class="topbl2"><a href="">Contact</a></div>
			<div class="clear"></div>
		</div>
		<div class="topa">Formularz</div>
	</div>
	<div class="center">
		<div class="centerc">
			<form id="formularz">
				<div id="exception"></div>
				<div>Imię:</div>
				<div><input type="text" name= "imie" id="imie"/></div>
				<div class="clear"></div>
				<div>Nazwisko:</div>
				<div><input type="text" name= "nazwisko" id="nazwisko"/></div>
				<div class="clear"></div>
				<div>Miasto:</div>
				<div><input type="text" name= "miasto" id="miasto"/></div>
				<div class="clear"></div>
				<div>Ulica:</div>
				<div><input type="text" name= "ulice" id="ulice"/></div>
				<div class="clear"></div>
				<div>Numer domu:</div>
				<div><input type="text" name= "numer domu" id="numerdomu"/></div>
				<div class="clear"></div>
				<div>Numer mieszkania:</div>
				<div><input type="text" name= "numer mieszkania" id="numermieszkania"/></div>
				<div class="clear"></div>
				<div>Data urodzenia:</div>
				<div><input type="text" name= "datę urodzenia" id="dateurodzenia" placeholder="01-01-2000"/></div>
				<div class="clear"></div>
				<div>Numer telefonu:</div>
				<div><input type="text" name= "numer telefonu" id="numertelefonu" placeholder="48666777888"/></div>
				<div class="clear"></div>
				<div>Email:</div>
				<div><input type="text" name= "email" id="email"/></div>
				<div class="clear"></div>
				<div>Płeć:</div>
				<div><input type = "radio" name="płeć" checked value="Kobieta"/>Kobieta <input type = "radio" name="płeć" value="Mężczyzna"/>Mężczyzna </div>
				<div class="clear"></div>
				<input type="reset" name="p2" value="Czyść"/>
    			<input type="button" name="p3" value="Wyślij" onclick="wynik()" />
			</form>
		</div>	
		</div>
</div>
<script src="{% static 'js/regularne2.js' %}"></script>
{% endblock content %}